# The directory of our training data
dataset_file: "../DNN-RE-data-new/MB-1004-GE-2Hist/data.csv"
# The name of our dataset
dataset_name: 'MB-1004-GE-2Hist'
# Number of split folds for our training
n_folds: 5
# Our neural network training hyper-parameters
hyperparameters:
    batch_size: 16
    epochs: 50
    layer_units: [128, 64]
# How many trials we will attempt for finding our best initialisation
initialisation_trials: 5
# The rule extractor we will use (if not given, we assume DeepRED_C5 is used)
rule_extractor: "DeepRED_C5"
# Where are we dumping our results. If not given, then it will be the same
# directory as the one containing the dataset.
output_dir: "experiment_results"