import setuptools

with open("README.md", "r") as f:
    long_description = f.read()

setuptools.setup(
    name="dnn_rem",  # Replace with your own username
    version="0.0.1",
    author="Artificial Intelligence Group - University of Cambridge",
    author_email="zs315@cam.ac.uk",
    description="Deep neural network rule extraction methods",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/mateoespinosa/rem",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6, <3.9',
    install_requires=[
        "absl-py==0.11.0",
        "astunparse==1.6.3",
        "attrs==20.2.0",
        "bunch==1.0.1",
        "cachetools==4.1.1",
        "certifi==2020.6.20",
        "cffi==1.14.3",
        "chardet==3.0.4",
        "gast==0.3.3",
        "google-auth==1.23.0",
        "google-auth-oauthlib==0.4.2",
        "google-pasta==0.2.0",
        "grpcio==1.33.2",
        "h5py==2.10.0",
        "idna==2.10",
        "importlib-metadata==2.0.0",
        "iniconfig==1.1.1",
        "Jinja2==2.11.2",
        "joblib==0.17.0",
        "Keras-Preprocessing==1.1.2",
        "Markdown==3.3.3",
        "MarkupSafe==1.1.1",
        "memory-profiler==0.58.0",
        "numpy<1.19.0",
        "oauthlib==3.1.0",
        "opt-einsum==3.3.0",
        "packaging==20.4",
        "pandas==0.25.3",
        "pluggy==0.13.1",
        "protobuf==3.13.0",
        "psutil==5.7.3",
        "py==1.9.0",
        "pyasn1==0.4.8",
        "pyasn1-modules==0.2.8",
        "pycparser==2.20",
        "pyparsing==2.4.7",
        "pytest==6.1.2",
        "python-dateutil==2.8.1",
        "pytz==2020.1",
        "PyYAML==5.3.1",
        "requests==2.24.0",
        "requests-oauthlib==1.3.0",
        "rpy2==3.3.6",
        "rsa==4.6",
        "scikit-learn==0.23.2",
        "scipy==1.5.3",
        "six==1.15.0",
        "sklearn==0.0",
        "tensorboard==2.3.0",
        "tensorboard-plugin-wit==1.7.0",
        "tensorflow==2.3.1",
        "tensorflow-estimator==2.3.0",
        "termcolor==1.1.0",
        "threadpoolctl==2.1.0",
        "toml==0.10.2",
        "tqdm==4.51.0",
        "tzlocal==2.1",
        "urllib3==1.25.11",
        "Werkzeug==1.0.1",
        "wrapt==1.12.1",
        "zipp==3.4.0",
    ]
)
